version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
build:
  project: ImperialLibrary.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    mkdir artifacts



    xcopy ".\Client\bin\Release\net452\*" "artifacts\Client\" /E /I /Y



    xcopy ".\Server\bin\Release\netstandard2.0\*" "artifacts\Server\" /E /I /Y



    copy "README.md" "artifacts\"



    7z a ImperialLibrary-%VERSION_NAME%.zip -r "artifacts\*"



    appveyor PushArtifact ImperialLibrary-%VERSION_NAME%.zip
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: '[Release] ImperialLibrary-$(appveyor_build_version)'
  description: ImperialLibrary version v$(appveyor_build_version)
  auth_token:
    secure: Hw8d95jOk9+v5QZDK3UbueRKyvYMyht+W5r38JVngeqMB4sC+7V8cRwmGwu7rJbp
  on:
    APPVEYOR_REPO_TAG: true